### PR TITLE
Create Features Section on FeaturesSection branch

### PR DESCRIPTION
**Pull request by AjMor01**
3 cards features section.
For the layout, I have used a combination of CSS Grid and FlexBox. 
For naming the CSS classes I followed the BEM methodology. 
Please feel free to share your feedback. Thank you guys.

### CODE REVIEW

**Comment by AjeaSmith** [comment]
Hey Ajmor01, Great work on this! the only thing I would suggest you adding would be to make the "feature-section" a Flexbox that way the 3 cards can stack on top of each other when on a mobile view. Then, on desktop view(using media query) they will be side-by-side that way the cards are responsive as well :) 

Heres a codepen I created demonstrating what I mean [https://codepen.io/ajeas/pen/gOORWYd?editors=1100] 

You should be good to go after this, great work!

**Comment by AjeaSmith** [comment]
Feel free to message me if you have any questions! 👍

**Comment by AjMor01** [comment]
hi, I did some changes to the layout. Now it shows three different behaviors depending on the viewport size, for mobile, tablet and desktop.
Thanks for the codepen, very helpful :)

**Comment by AjeaSmith** [comment]
Great work!

**Pull request merged**
